name: diary
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-167.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
